## Exploratory Data Analysis

Common EDA technoques

#### Exploring data
Example:
Filetring
Sorting
Grouping

#### Visualizing data
Example: Histograms
ScatterPlot
Pair Plots

In [1]:
import pandas as pd 
import numpy as np

In [4]:
df=pd.read_pickle('../Gathering and Cleaning  Data/groceries_with_new_columna.pkl')
df

,Product_ID,Product_Id_No,Category,SubCategory,Price_Dollars,Inventory,Pecentage Inventory,Inventory Flag,Last_Updated,LastUpdatedTiime,Next_Scheduled_Shipment,Shipment_Date_Dow
0,P100010,100010,Produce,Fruit,1.50,349,7.19,,2023-06-12 15:35:00,15:35:00,2023-06-15,Thursday
1,P100011,100011,Produce,Fruit,0.40,500,10.29,,2023-06-12 18:30:00,18:30:00,2023-06-15,Thursday
2,P100012,100012,Produce,Fruit,4.00,200,4.12,,2023-06-12 17:22:00,17:22:00,2023-06-15,Thursday
3,P100013,100013,Produce,Fruit,0.99,50,1.03,,2023-06-12 16:29:00,16:29:00,2023-06-15,Thursday
4,P100014,100014,Produce,Fruit,3.99,148,3.05,,2023-06-12 18:10:00,18:10:00,2023-06-15,Thursday
5,P100015,100015,Produce,Fruit,5.99,99,2.04,,2023-06-12 19:15:00,19:15:00,2023-06-15,Thursday
6,P100016,100016,Produce,Vegetable,1.78,78,1.61,,2023-06-12 19:25:00,19:25:00,2023-06-15,Thursday
7,P100017,100017,Produce,Vegetable,2.00,200,4.12,,2023-06-12 18:05:00,18:05:00,2023-06-15,Thursday
8,P100018,100018,Produce,Vegetable,1.99,50,1.03,,2023-06-12 16:42:00,16:42:00,2023-06-15,Thursday
9,P100019,100019,Produce,Vegetable,0.99,230,4.74,,2023-06-12 17:47:00,17:47:00,2023-06-15,Thursday
10,P100020,100020,Produce,Meat,8.99,145,2.99,,2023-06-13 07:00:00,07:00:00,2023-06-17,Saturday
11,P100021,100021,Produce,Meat,10.49,284,5.85,,2023-06-13 07:20:00,07:20:00,2023-06-17,Saturday
12,P100022,100022,Produce,Meat,7.99,188,3.87,,2023-06-13 07:32:00,07:32:00,2023-06-17,Saturday
13,P100023,100023,Produce,Dairy,3.50,400,8.24,,2023-06-13 08:35:00,08:35:00,2023-06-17,Saturday
14,P100024,100024,Produce,Dairy,3.29,234,4.82,,2023-06-13 08:54:00,08:54:00,2023-06-17,Saturday
15,P100025,100025,Produce,Dairy,4.49,32,0.66,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
16,P100026,100026,Produce,Dairy,1.00,432,8.89,,2023-06-13 08:41:00,08:41:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,1.50,27,0.56,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
18,P100028,100028,Pantry,Snacks,2.50,365,7.51,,2023-06-10 12:12:00,12:12:00,2023-06-24,Saturday
19,P100029,100029,Pantry,Snacks,5.39,340,7.00,,2023-06-10 12:24:00,12:24:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,2.99,5,0.10,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday
21,P100031,100031,Frozen,Frozen Snacks,6.99,85,1.75,,2023-05-28 22:02:00,22:02:00,2023-06-28,Wednesday
22,P100032,100032,Frozen,Frozen Snacks,4.96,76,1.56,,2023-05-28 22:05:00,22:05:00,2023-06-28,Wednesday
23,P100033,100033,Frozen,Frozen Fruit,10.99,162,3.34,,2023-05-28 22:14:00,22:14:00,2023-06-28,Wednesday
24,P100034,100034,Frozen,Frozen Fruit,7.96,178,3.66,,2023-05-28 22:11:00,22:11:00,2023-06-28,Wednesday

In [11]:
#DEMO: filtering 
df.loc[df['Inventory Flag']=='Low Inventory', Price_Dollars]

,Product_ID,Product_Id_No,Category,SubCategory,Price_Dollars,Inventory,Pecentage Inventory,Inventory Flag,Last_Updated,LastUpdatedTiime,Next_Scheduled_Shipment,Shipment_Date_Dow
15,P100025,100025,Produce,Dairy,4.49,32,0.66,Low Inventory,2023-06-13 08:37:00,08:37:00,2023-06-17,Saturday
17,P100027,100027,Pantry,Snacks,1.50,27,0.56,Low Inventory,2023-06-10 12:02:00,12:02:00,2023-06-24,Saturday
20,P100030,100030,Pantry,Snacks,2.99,5,0.10,Low Inventory,2023-06-10 12:38:00,12:38:00,2023-06-24,Saturday